### ISSUE TITLE
error on first install

### ISSUE THREAD

**Issue by DemonBigj781** [GaslampStudios/VintageLauncher#5] opened 2023-03-10 17:48 UTC
**Describe the bug**
this happens on first install. when accepting the prompt to move the mods folder

**To Reproduce**
1. install launcher
2. accept moving the mods folder.

**Expected behavior**
the mods folder moved

**Screenshots**
![image](https://user-images.githubusercontent.com/20097331/224386975-cbd31bce-a6cf-48ab-8c8d-665881bc39d6.png)
![Screenshot (10)](https://user-images.githubusercontent.com/20097331/224388153-a71cb914-2091-42b5-aaae-2bf7d518157a.png)

**Desktop (please complete the following information):**
 - OS: win 11
 - Browser: brave
 - Version 1.48.171

**Smartphone (please complete the following information):**
 - Device: samsung s10e
 - OS: andriod 11
 - Browser brave
 - Version 1.48.171

**Additional context**
the standard installation is on  c drive root

**Comment by GaslampStudios** [comment] 2023-03-10 18:52
Confirmed issue with reading CS or DLL files into the mod vault. Probable duplicate of [issue #2](https://github.com/GaslampStudios/VintageLauncher/issues/2).

**Comment by DemonBigj781** [comment] 2023-03-10 19:57
thanks for the information

**Comment by GaslampStudios** [comment] 2023-03-13 16:47
Closed as duplicate

**Closed as completed by GaslampStudios** 2023-03-13 16:47 UTC
Labels: confirmed, duplicate
